[package]
name = "bluec"
version = "0.5.0"
edition = "2024"
authors = ["Neil Henderson <neil@bluetarpmedia.com>"]
description = "The BlueC compiler driver binary executable. Requires `gcc` for the preprocessor and assembler."

[dependencies]
libbluec = { path = "../libbluec" }
