name: Build BlueC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --check

      - name: Cargo clippy
        run: cargo clippy --workspace -- -D warnings
  
  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            results_file: test-results.xml
          - os: macos-latest
            # We don't want our test badge to include the results twice; it looks for "*test*.xml" filenames
            # so we'll just take the ubuntu results for the badge.
            results_file: macos-results.xml
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Print Rust version
        run: rustc --version

      - name: Run tests
        run: |
          cargo install cargo2junit --locked
          RUSTC_BOOTSTRAP=1 cargo test -- -Z unstable-options --format json --report-time | tee results.json
          cat results.json | cargo2junit > ${{ matrix.results_file }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: ${{ matrix.results_file }}
          retention-days: 7
          
      - name: Publish test badge JSON to Gist
        # We don't want our test badge to have duplicates so just do this once for ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: ${{ secrets.TEST_BADGE_GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}
          prefix: bluec

  # Build in Release but only on 'main' branch
  release-build:
    if: github.ref == 'refs/heads/main'
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Print Rust version
        run: rustc --version

      - name: Build release
        run: cargo build --release --verbose
